//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rozliczenie_Kilometrów.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozliczenie
    {
        public Nullable<decimal> Drive_List { get; set; }
        public Nullable<decimal> Traveled_Way { get; set; }
        public Nullable<decimal> Fuel_Used { get; set; }
        public Nullable<decimal> Fuel_Standard { get; set; }
        public Nullable<System.DateTime> Data_ { get; set; }
        public byte[] Statistics { get; set; }
        public int Key { get; set; }
    }
}
